//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public equipo()
        {
            this.laboratorio = new HashSet<laboratorio>();
        }
    
        public int id_equipo { get; set; }
        public string config { get; set; }
        public string software { get; set; }
        public string sistOper { get; set; }
        public string servidores { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<laboratorio> laboratorio { get; set; }
    }
}
