//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class laboratorio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public laboratorio()
        {
            this.solicitud = new HashSet<solicitud>();
        }
    
        public int id_lab { get; set; }
        public Nullable<byte> cantCompu { get; set; }
        public Nullable<byte> piso { get; set; }
        public Nullable<bool> aire { get; set; }
        public Nullable<bool> videoBeam { get; set; }
        public Nullable<bool> disponible { get; set; }
        public Nullable<int> id_equipo { get; set; }
    
        public virtual equipo equipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<solicitud> solicitud { get; set; }
    }
}
