//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitud
    {
        public int id_solic { get; set; }
        public Nullable<int> id_lab { get; set; }
        public string id_curso { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora_ini { get; set; }
        public Nullable<System.TimeSpan> hora_fin { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual curso curso { get; set; }
        public virtual laboratorio laboratorio { get; set; }
    }
}
